version: '3.8'

services:
	postgres:
		image: postgres:15-alpine
		container_name: mastro-postgres
		environment:
			POSTGRES_DB: ${POSTGRES_DB:-mastro}
			POSTGRES_USER: ${POSTGRES_USER:-mastro}
			POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
			PGDATA: /var/lib/postgresql/data/pgdata
		volumes:
			- postgres_data:/var/lib/postgresql/data
		restart: unless-stopped
		networks:
			- mastro-network
		healthcheck:
			test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-mastro}"]
			interval: 10s
			timeout: 5s
			retries: 5

volumes:
	postgres_data:
		driver: local

networks:
	mastro-network:
		driver: bridge

